name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov build numpy pandas netCDF4 pyarrow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./checker --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./checker --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test coverage
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GMAIL_AUTHORIZED_USER_TOKEN: ${{ secrets.GMAIL_AUTHORIZED_USER_TOKEN }}
        run: |
          python -m pytest --cov ./checker
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
